$color = rgba(0, 0, 0, 1)
$inner_color = rgba(0, 0, 0, 0.66)
$outer_color = rgba(133, 167, 245, 1)
$font_color = rgba(154, 255, 255, 1)
$placeholder_color = rgba(154, 255, 255, 0.7)
$check_color = rgba(103, 230, 255, 1)

$accent_color = rgba(77, 129, 183, 1)
$yellow_color = rgba(156, 157, 209, 1)
$red_color = rgba(138, 140, 201, 1)
$green_color = rgba(96, 209, 239, 1)
$orange_color = rgba(156, 157, 209, 1)
$fail_color = rgba(138, 140, 201, 1)
