# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgb(4d81b7)
$inactiveBorderColor = rgba(686163aa)

# Window Rules
windowrule = match:class ^OmarchyFloatingTerm$, float on, center on, size 40% 60%

general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    layout = dwindle
}

decoration {
    rounding = 12
    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = yes
    bezier = calm, 0.25, 0.9, 0.35, 1

    animation = windows,     1, 4, calm
    animation = windowsIn,   1, 4, calm
    animation = windowsOut,  1, 3, calm
    animation = windowsMove, 1, 4, calm
    animation = fade,        1, 3, calm
    animation = workspaces,  1, 4, calm
    animation = layers,      1, 3, calm
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor

    groupbar {
        col.active = $activeBorderColor
        col.inactive = $inactiveBorderColor
        font_family = JetBrainsMono Nerd Font
        font_size = 10
    }
}
